#!/usr/bin/env bash

files=()
opts=()
target=""
no_rm_pp=true

expect_target=false

for arg in "$@"; do
  if [ "$expect_target" = true ]; then
    target="$arg"
    expect_target=false
    continue
  fi

  case "$arg" in
    -E)
      no_rm_pp=false
      ;;
    -o)
      #opts+=("$arg")
      expect_target=true
      ;;
    -*)
      opts+=("$arg")
      ;;
    *)
      files+=("$arg")
      ;;
  esac
done

#base="${1}"
base="${files[0]%.c}"
shift

if test -z "$target"
then
    target=${base}
fi

ncc ${opts[@]} ${base}.c
echo clang ${opts[@]} -o ${target} ${base}.c.c 2> ${base}.c.error 
if clang ${opts[@]} -o ${target} ${base}.c.c 2> ${base}.c.error 
then
    rm ${base}.c.error
    if test $no_rm_pp = true
    then
        rm ${base}.c.i
    fi
else
    cat ${base}.c.error | grep error; exit 3
fi
