#!/usr/bin/env bash

CC=clang

files=()
opts=()
libs=()
obj_files=()
target=""
no_rm_pp=true

expect_target=false
compile_only=false
all_object_file=true
m5stack=false
pico=false

for arg in "$@"; do
  if [ "$expect_target" = true ]; then
    target="$arg"
    expect_target=false
    continue
  fi

  case "$arg" in
    -E)
      no_rm_pp=false
      ;;
    -gcc)
      CC=gcc
      ;;
    -pico)
      opts+=("-D__PICO__")
      pico=true
      ;;
    -m5stack)
      opts+=("-m5stack")
      opts+=("-D__M5STACK__")
      opts+=("-cpp")
      opts+=("-uniq")
      m5stack=true
      ;;
    -cpp)
      CC=clang++
      ;;
    -o)
      #opts+=("$arg")
      expect_target=true
      ;;
    -c)
      compile_only=true
      #opts+=("$arg")
      ;;
    -l*)
      libs+=("$arg")
      ;;
    -*)
      opts+=("$arg")
      ;;
    *.o) 
      obj_files+=("$arg")
      ;;
    *.nc)
      files+=("$arg")
      all_object_file=false
      ;;
    *)
      files+=("$arg")
      all_object_file=false
      ;;
  esac
done

# base for output/error path (keeps source directory)
base="${files[0]%.nc}"
# ncc writes transpiled C into current directory using basename
cbase="$(basename "${base}")"

if [ "$CC" == clang++ ]
then
    ncc ${opts[@]} -cpp ${files[0]}
else
    ncc ${opts[@]} ${files[0]}
fi

transpile_ok=$?

if [ "$pico" == true ]
then
    echo pico
    exit 0
elif [ "$m5stack" == true ]
then
    echo m5stack
    exit 0
elif [ "$all_object_file" == true ]
then
    $CC ${opts[@]} -o ${target} ${files[@]} -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/boehmgc/lib -L/opt/homebrew/opt/zstd/lib -I/opt/homebrew/opt/openssl/include -L/opt/homebrew/opt/ncurses/lib ${obj_files[@]} ${libs[@]}
elif test $transpile_ok = 0
then
    if test $compile_only = true
    then
        if test -z "$target"
        then
            target=${base}.o
        fi
        
        #echo $CC -c ${opts[@]} -o ${target} ${cbase}.c 2> ${base}.c.error 
        if $CC -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/boehmgc/lib -L/opt/homebrew/opt/zstd/lib -I/opt/homebrew/opt/openssl/include -L/opt/homebrew/opt/ncurses/lib -c ${opts[@]} -o ${target} ${cbase}.c ${libs[@]} 2> ${base}.c.error
        then
            rm -f ${base}.c.error
            if test $no_rm_pp = true
            then
                rm -f ${base}.nc.i
            fi
        else
            cat ${base}.c.error | grep error; exit 3
        fi
    else 
        if test -z "$target"
        then
            target=${base}
        fi
        
        #echo $CC ${opts[@]} -o ${target} ${cbase}.c 2> ${base}.c.error 
        if $CC -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/boehmgc/lib -L/opt/homebrew/opt/zstd/lib -I/opt/homebrew/opt/openssl/include ${opts[@]} -L/opt/homebrew/opt/ncurses/lib -o ${target} ${cbase}.c ${obj_files[@]} ${libs[@]} 2> ${base}.c.error
        then
            rm -f ${base}.c.error
            if test $no_rm_pp = true
            then
                rm -f ${base}.nc.i
            fi
        else
            cat ${base}.c.error | grep error; exit 3
        fi
    fi
fi    
