/// c_include definition ///
/// typedef definition ///
typedef unsigned long size_t;

typedef int wchar_t;

typedef unsigned long  long    ;

typedef __builtin_va_list __gnuc_va_list;

typedef unsigned char __u_char;

typedef unsigned short int __u_short;

typedef unsigned int __u_int;

typedef unsigned long  int __u_long;

typedef char __int8_t;

typedef unsigned char __uint8_t;

typedef short int __int16_t;

typedef unsigned short int __uint16_t;

typedef int __int32_t;

typedef unsigned int __uint32_t;

typedef long  int __int64_t;

typedef unsigned long  int __uint64_t;

typedef char  __int_least8_t  ;

typedef unsigned char  __uint_least8_t  ;

typedef short int  __int_least16_t  ;

typedef unsigned short int  __uint_least16_t  ;

typedef int  __int_least32_t  ;

typedef unsigned int  __uint_least32_t  ;

typedef long  int  __int_least64_t  ;

typedef unsigned long  int  __uint_least64_t  ;

typedef long  int __quad_t;

typedef unsigned long  int __u_quad_t;

typedef long  int __intmax_t;

typedef unsigned long  int __uintmax_t;

typedef unsigned long  int __dev_t;

typedef unsigned int __uid_t;

typedef unsigned int __gid_t;

typedef unsigned long  int __ino_t;

typedef unsigned long  int __ino64_t;

typedef unsigned int __mode_t;

typedef unsigned long  int __nlink_t;

typedef long  int __off_t;

typedef long  int __off64_t;

typedef int __pid_t;

typedef struct __fsid_t  __fsid_t  ;

typedef long  int __clock_t;

typedef unsigned long  int __rlim_t;

typedef unsigned long  int __rlim64_t;

typedef unsigned int __id_t;

typedef long  int __time_t;

typedef unsigned int __useconds_t;

typedef long  int __suseconds_t;

typedef long  int __suseconds64_t;

typedef int __daddr_t;

typedef int __key_t;

typedef int __clockid_t;

typedef void* __timer_t;

typedef long  int __blksize_t;

typedef long  int __blkcnt_t;

typedef long  int __blkcnt64_t;

typedef unsigned long  int __fsblkcnt_t;

typedef unsigned long  int __fsblkcnt64_t;

typedef unsigned long  int __fsfilcnt_t;

typedef unsigned long  int __fsfilcnt64_t;

typedef long  int __fsword_t;

typedef long  int __ssize_t;

typedef long  int __syscall_slong_t;

typedef unsigned long  int __syscall_ulong_t;

typedef long  int  __loff_t  ;

typedef char* __caddr_t;

typedef long  int __intptr_t;

typedef unsigned int __socklen_t;

typedef int __sig_atomic_t;

typedef struct anonymous_typeX1 __mbstate_t;

typedef struct _G_fpos_t  __fpos_t  ;

typedef struct _G_fpos64_t  __fpos64_t  ;

typedef struct _IO_FILE  __FILE  ;

typedef struct _IO_FILE  FILE  ;

typedef void _IO_lock_t;

typedef long  int (*cookie_read_function_t)(void*,char*,unsigned long );

typedef long  int (*cookie_write_function_t)(void*,const char*,unsigned long );

typedef int (*cookie_seek_function_t)(void*,long  int* ,int);

typedef int (*cookie_close_function_t)(void*);

typedef struct _IO_cookie_io_functions_t  cookie_io_functions_t  ;

typedef __builtin_va_list  va_list  ;

typedef long  int  off_t  ;

typedef long  int  off64_t  ;

typedef long  int  ssize_t  ;

typedef struct _G_fpos_t  fpos_t  ;

typedef struct _G_fpos64_t  fpos64_t  ;

typedef float float_t;

typedef double double_t;

/// previous struct definition ///
struct _IO_FILE;

struct _IO_marker;

struct _IO_codecvt;

struct _IO_wide_data;

struct obstack;

/// struct definition ///
struct __fsid_t
{
    int __val[2];
};

union anonymous_typeZ2
{
unsigned int __wch;
char __wchb[4];
};

union anonymous_typeZ3
{
unsigned int __wch;
char __wchb[4];
};

struct anonymous_typeX1
{
    int __count;
    union {
        unsigned int __wch;
        char __wchb[4];
    } __value;
};

struct _G_fpos_t
{
    long  int  __pos  ;
    struct {
        int __count;
        union {
            unsigned int __wch;
            char __wchb[4];
        } __value;
    } __state;
};

struct _G_fpos64_t
{
    long  int  __pos  ;
    struct {
        int __count;
        union {
            unsigned int __wch;
            char __wchb[4];
        } __value;
    } __state;
};

struct _IO_FILE
{
    int _flags;
    char* _IO_read_ptr;
    char* _IO_read_end;
    char* _IO_read_base;
    char* _IO_write_base;
    char* _IO_write_ptr;
    char* _IO_write_end;
    char* _IO_buf_base;
    char* _IO_buf_end;
    char* _IO_save_base;
    char* _IO_backup_base;
    char* _IO_save_end;
    struct _IO_marker*  _markers  ;
    struct _IO_FILE*  _chain  ;
    int _fileno;
    int _flags2:24;
    char _short_backupbuf[1];
    long  int  _old_offset  ;
    unsigned short int _cur_column;
    char _vtable_offset;
    char _shortbuf[1];
    void*  _lock  ;
    long  int  _offset  ;
    struct _IO_codecvt*  _codecvt  ;
    struct _IO_wide_data*  _wide_data  ;
    struct _IO_FILE*  _freeres_list  ;
    void* _freeres_buf;
    struct _IO_FILE**  _prevchain  ;
    int _mode;
    int _unused3;
    unsigned long  int  _total_written  ;
    char _unused2[12*sizeof(int)-5*sizeof(void*)];
};

struct _IO_cookie_io_functions_t
{
    long  int (*(*read))(void*,char*,unsigned long )  ;
    long  int (*(*write))(void*,const char*,unsigned long )  ;
    int (*(*seek))(void*,long  int* ,int)  ;
    int (*(*close))(void*)  ;
};

enum { FP_INT_UPWARD=(0),
FP_INT_DOWNWARD=(1),
FP_INT_TOWARDZERO=(2),
FP_INT_TONEARESTFROMZERO=(3),
FP_INT_TONEAREST=(4)
};

enum { FP_NAN=(0),
FP_INFINITE=(1),
FP_ZERO=(2),
FP_SUBNORMAL=(3),
FP_NORMAL=(4)
};

/// variable definition ///
extern struct _IO_FILE*  stdin  ;
extern struct _IO_FILE*  stdout  ;
extern struct _IO_FILE*  stderr  ;
extern int signgam;
// source head

// header function
int remove(const char* __filename);
int rename(const char* __old, const char* __new);
int renameat(int __oldfd, const char* __old, int __newfd, const char* __new);
int renameat2(int __oldfd, const char* __old, int __newfd, const char* __new, unsigned int __flags);
int fclose(struct _IO_FILE*  __stream  );
struct _IO_FILE*  tmpfile() __attribute__ ((__malloc__))  ;
struct _IO_FILE*  tmpfile64() __attribute__ ((__malloc__))  ;
char* tmpnam(char [20]);
char* tmpnam_r(char __s[20]);
char* tempnam(const char* __dir, const char* __pfx) __attribute__ ((__malloc__))  ;
int fflush(struct _IO_FILE*  __stream  );
int fflush_unlocked(struct _IO_FILE*  __stream  );
int fcloseall();
struct _IO_FILE*  fopen(const char* __restrict __filename, const char* __restrict __modes) __attribute__ ((__malloc__))  ;
struct _IO_FILE*  freopen(const char* __restrict __filename, const char* __restrict __modes, struct _IO_FILE* __restrict  __stream  );
struct _IO_FILE*  fopen64(const char* __restrict __filename, const char* __restrict __modes) __attribute__ ((__malloc__))  ;
struct _IO_FILE*  freopen64(const char* __restrict __filename, const char* __restrict __modes, struct _IO_FILE* __restrict  __stream  );
struct _IO_FILE*  fdopen(int __fd, const char* __modes) __attribute__ ((__malloc__))  ;
struct _IO_FILE*  fopencookie(void* __restrict __magic_cookie, const char* __restrict __modes, struct _IO_cookie_io_functions_t  __io_funcs  ) __attribute__ ((__malloc__))  ;
struct _IO_FILE*  fmemopen(void* __s, unsigned long  __len  , const char* __modes) __attribute__ ((__malloc__))  ;
struct _IO_FILE*  open_memstream(char** __bufloc, unsigned long*  __sizeloc  ) __attribute__ ((__malloc__))  ;
void setbuf(struct _IO_FILE* __restrict  __stream  , char* __restrict __buf);
int setvbuf(struct _IO_FILE* __restrict  __stream  , char* __restrict __buf, int __modes, unsigned long  __n  );
void setbuffer(struct _IO_FILE* __restrict  __stream  , char* __restrict __buf, unsigned long  __size  );
void setlinebuf(struct _IO_FILE*  __stream  );
int fprintf(struct _IO_FILE* __restrict  __stream  , const char* __restrict __format, ...);
int printf(const char* __restrict __format, ...);
int sprintf(char* __restrict __s, const char* __restrict __format, ...);
int vfprintf(struct _IO_FILE* __restrict  __s  , const char* __restrict __format, __builtin_va_list  __arg  );
int vprintf(const char* __restrict __format, __builtin_va_list  __arg  );
int vsprintf(char* __restrict __s, const char* __restrict __format, __builtin_va_list  __arg  );
int snprintf(char* __restrict __s, unsigned long  __maxlen  , const char* __restrict __format, ...) __attribute__ ((__format__ (__printf__, 3, 4)));
int vsnprintf(char* __restrict __s, unsigned long  __maxlen  , const char* __restrict __format, __builtin_va_list  __arg  ) __attribute__ ((__format__ (__printf__, 3, 0)));
int vasprintf(char** __restrict __ptr, const char* __restrict __f, __builtin_va_list  __arg  ) __attribute__ ((__format__ (__printf__, 2, 0))) ;
int __asprintf(char** __restrict __ptr, const char* __restrict __fmt, ...) __attribute__ ((__format__ (__printf__, 2, 3))) ;
int asprintf(char** __restrict __ptr, const char* __restrict __fmt, ...) __attribute__ ((__format__ (__printf__, 2, 3))) ;
int vdprintf(int __fd, const char* __restrict __fmt, __builtin_va_list  __arg  ) __attribute__ ((__format__ (__printf__, 2, 0)));
int dprintf(int __fd, const char* __restrict __fmt, ...) __attribute__ ((__format__ (__printf__, 2, 3)));
int fscanf(struct _IO_FILE* __restrict  __stream  , const char* __restrict __format, ...);
int scanf(const char* __restrict __format, ...);
int sscanf(const char* __restrict __s, const char* __restrict __format, ...);
int __isoc23_fscanf(struct _IO_FILE* __restrict  __stream  , const char* __restrict __format, ...);
int __isoc23_scanf(const char* __restrict __format, ...);
int __isoc23_sscanf(const char* __restrict __s, const char* __restrict __format, ...);
int vfscanf(struct _IO_FILE* __restrict  __s  , const char* __restrict __format, __builtin_va_list  __arg  ) __attribute__ ((__format__ (__scanf__, 2, 0)))  ;
int vscanf(const char* __restrict __format, __builtin_va_list  __arg  ) __attribute__ ((__format__ (__scanf__, 1, 0))) ;
int vsscanf(const char* __restrict __s, const char* __restrict __format, __builtin_va_list  __arg  ) __attribute__ ((__format__ (__scanf__, 2, 0)));
int __isoc23_vfscanf(struct _IO_FILE* __restrict  __s  , const char* __restrict __format, __builtin_va_list  __arg  );
int __isoc23_vscanf(const char* __restrict __format, __builtin_va_list  __arg  );
int __isoc23_vsscanf(const char* __restrict __s, const char* __restrict __format, __builtin_va_list  __arg  );
int fgetc(struct _IO_FILE*  __stream  );
int getc(struct _IO_FILE*  __stream  );
int getchar();
int getc_unlocked(struct _IO_FILE*  __stream  );
int getchar_unlocked();
int fgetc_unlocked(struct _IO_FILE*  __stream  );
int fputc(int __c, struct _IO_FILE*  __stream  );
int putc(int __c, struct _IO_FILE*  __stream  );
int putchar(int __c);
int fputc_unlocked(int __c, struct _IO_FILE*  __stream  );
int putc_unlocked(int __c, struct _IO_FILE*  __stream  );
int putchar_unlocked(int __c);
int getw(struct _IO_FILE*  __stream  );
int putw(int __w, struct _IO_FILE*  __stream  );
char* fgets(char* __restrict __s, int __n, struct _IO_FILE* __restrict  __stream  );
char* fgets_unlocked(char* __restrict __s, int __n, struct _IO_FILE* __restrict  __stream  );
long  int  __getdelim(char** __restrict __lineptr, unsigned long* __restrict  __n  , int __delimiter, struct _IO_FILE* __restrict  __stream  );
long  int  getdelim(char** __restrict __lineptr, unsigned long* __restrict  __n  , int __delimiter, struct _IO_FILE* __restrict  __stream  );
long  int  getline(char** __restrict __lineptr, unsigned long* __restrict  __n  , struct _IO_FILE* __restrict  __stream  );
int fputs(const char* __restrict __s, struct _IO_FILE* __restrict  __stream  );
int puts(const char* __s);
int ungetc(int __c, struct _IO_FILE*  __stream  );
unsigned long  fread(void* __restrict __ptr, unsigned long  __size  , unsigned long  __n  , struct _IO_FILE* __restrict  __stream  );
unsigned long  fwrite(const void* __restrict __ptr, unsigned long  __size  , unsigned long  __n  , struct _IO_FILE* __restrict  __s  );
int fputs_unlocked(const char* __restrict __s, struct _IO_FILE* __restrict  __stream  );
unsigned long  fread_unlocked(void* __restrict __ptr, unsigned long  __size  , unsigned long  __n  , struct _IO_FILE* __restrict  __stream  );
unsigned long  fwrite_unlocked(const void* __restrict __ptr, unsigned long  __size  , unsigned long  __n  , struct _IO_FILE* __restrict  __stream  );
int fseek(struct _IO_FILE*  __stream  , long  int __off, int __whence);
long  int ftell(struct _IO_FILE*  __stream  );
void rewind(struct _IO_FILE*  __stream  );
int fseeko(struct _IO_FILE*  __stream  , long  int  __off  , int __whence);
long  int  ftello(struct _IO_FILE*  __stream  );
int fgetpos(struct _IO_FILE* __restrict  __stream  , struct _G_fpos_t* __restrict  __pos  );
int fsetpos(struct _IO_FILE*  __stream  , const struct _G_fpos_t*  __pos  );
int fseeko64(struct _IO_FILE*  __stream  , long  int  __off  , int __whence);
long  int  ftello64(struct _IO_FILE*  __stream  );
int fgetpos64(struct _IO_FILE* __restrict  __stream  , struct _G_fpos64_t* __restrict  __pos  );
int fsetpos64(struct _IO_FILE*  __stream  , const struct _G_fpos64_t*  __pos  );
void clearerr(struct _IO_FILE*  __stream  );
int feof(struct _IO_FILE*  __stream  );
int ferror(struct _IO_FILE*  __stream  );
void clearerr_unlocked(struct _IO_FILE*  __stream  );
int feof_unlocked(struct _IO_FILE*  __stream  );
int ferror_unlocked(struct _IO_FILE*  __stream  );
void perror(const char* __s);
int fileno(struct _IO_FILE*  __stream  );
int fileno_unlocked(struct _IO_FILE*  __stream  );
int pclose(struct _IO_FILE*  __stream  );
struct _IO_FILE*  popen(const char* __command, const char* __modes) __attribute__ ((__malloc__))  ;
char* ctermid(char* __s);
char* cuserid(char* __s);
int obstack_printf(struct obstack* __restrict  __obstack  , const char* __restrict __format, ...) __attribute__ ((__format__ (__printf__, 2, 3)));
int obstack_vprintf(struct obstack* __restrict  __obstack  , const char* __restrict __format, __builtin_va_list  __args  ) __attribute__ ((__format__ (__printf__, 2, 0)));
void flockfile(struct _IO_FILE*  __stream  );
int ftrylockfile(struct _IO_FILE*  __stream  );
void funlockfile(struct _IO_FILE*  __stream  );
int __uflow(struct _IO_FILE*    );
int __overflow(struct _IO_FILE*    , int );
int __fpclassify(double __value) __attribute__ ((__const__));
int __signbit(double __value) __attribute__ ((__const__));
int __isinf(double __value) __attribute__ ((__const__));
int __finite(double __value) __attribute__ ((__const__));
int __isnan(double __value) __attribute__ ((__const__));
int __iseqsig(double __x, double __y);
int __issignaling(double __value) __attribute__ ((__const__));
double acos(double __x);
double __acos(double __x);
double asin(double __x);
double __asin(double __x);
double atan(double __x);
double __atan(double __x);
double atan2(double __y, double __x);
double __atan2(double __y, double __x);
double cos(double __x);
double __cos(double __x);
double sin(double __x);
double __sin(double __x);
double tan(double __x);
double __tan(double __x);
double acospi(double __x);
double __acospi(double __x);
double asinpi(double __x);
double __asinpi(double __x);
double atanpi(double __x);
double __atanpi(double __x);
double atan2pi(double __y, double __x);
double __atan2pi(double __y, double __x);
double cospi(double __x);
double __cospi(double __x);
double sinpi(double __x);
double __sinpi(double __x);
double tanpi(double __x);
double __tanpi(double __x);
double cosh(double __x);
double __cosh(double __x);
double sinh(double __x);
double __sinh(double __x);
double tanh(double __x);
double __tanh(double __x);
void sincos(double __x, double* __sinx, double* __cosx);
void __sincos(double __x, double* __sinx, double* __cosx);
double acosh(double __x);
double __acosh(double __x);
double asinh(double __x);
double __asinh(double __x);
double atanh(double __x);
double __atanh(double __x);
double exp(double __x);
double __exp(double __x);
double frexp(double __x, int* __exponent);
double __frexp(double __x, int* __exponent);
double ldexp(double __x, int __exponent);
double __ldexp(double __x, int __exponent);
double log(double __x);
double __log(double __x);
double log10(double __x);
double __log10(double __x);
double modf(double __x, double* __iptr);
double __modf(double __x, double* __iptr);
double exp10(double __x);
double __exp10(double __x);
double exp2m1(double __x);
double __exp2m1(double __x);
double exp10m1(double __x);
double __exp10m1(double __x);
double log2p1(double __x);
double __log2p1(double __x);
double log10p1(double __x);
double __log10p1(double __x);
double logp1(double __x);
double __logp1(double __x);
double expm1(double __x);
double __expm1(double __x);
double log1p(double __x);
double __log1p(double __x);
double logb(double __x);
double __logb(double __x);
double exp2(double __x);
double __exp2(double __x);
double log2(double __x);
double __log2(double __x);
double pow(double __x, double __y);
double __pow(double __x, double __y);
double sqrt(double __x);
double __sqrt(double __x);
double hypot(double __x, double __y);
double __hypot(double __x, double __y);
double cbrt(double __x);
double __cbrt(double __x);
double compoundn(double __x, long long int __y);
double __compoundn(double __x, long long int __y);
double pown(double __x, long long int __y);
double __pown(double __x, long long int __y);
double powr(double __x, double __y);
double __powr(double __x, double __y);
double rootn(double __x, long long int __y);
double __rootn(double __x, long long int __y);
double rsqrt(double __x);
double __rsqrt(double __x);
double ceil(double __x) __attribute__ ((__const__));
double fabs(double __x) __attribute__ ((__const__));
double floor(double __x) __attribute__ ((__const__));
double fmod(double __x, double __y);
double __fmod(double __x, double __y);
int isinf(double __value) __attribute__ ((__const__));
int finite(double __value) __attribute__ ((__const__));
double drem(double __x, double __y);
double __drem(double __x, double __y);
double significand(double __x);
double __significand(double __x);
double copysign(double __x, double __y) __attribute__ ((__const__));
double nan(const char* __tagb);
double __nan(const char* __tagb);
int isnan(double __value) __attribute__ ((__const__));
double j0(double );
double __j0(double );
double j1(double );
double __j1(double );
double jn(int , double );
double __jn(int , double );
double y0(double );
double __y0(double );
double y1(double );
double __y1(double );
double yn(int , double );
double __yn(int , double );
double erf(double );
double __erf(double );
double erfc(double );
double __erfc(double );
double lgamma(double );
double __lgamma(double );
double tgamma(double );
double __tgamma(double );
double gamma(double );
double __gamma(double );
double lgamma_r(double , int* __signgamp);
double __lgamma_r(double , int* __signgamp);
double rint(double __x);
double __rint(double __x);
double nextafter(double __x, double __y);
double __nextafter(double __x, double __y);
double nexttoward(double __x, long  double __y);
double __nexttoward(double __x, long  double __y);
double nextdown(double __x);
double __nextdown(double __x);
double nextup(double __x);
double __nextup(double __x);
double remainder(double __x, double __y);
double __remainder(double __x, double __y);
double scalbn(double __x, int __n);
double __scalbn(double __x, int __n);
int ilogb(double __x);
int __ilogb(double __x);
long  int llogb(double __x);
long  int __llogb(double __x);
double scalbln(double __x, long  int __n);
double __scalbln(double __x, long  int __n);
double nearbyint(double __x);
double __nearbyint(double __x);
double round(double __x) __attribute__ ((__const__));
double trunc(double __x) __attribute__ ((__const__));
double remquo(double __x, double __y, int* __quo);
double __remquo(double __x, double __y, int* __quo);
long  int lrint(double __x);
long  int __lrint(double __x);
long long int llrint(double __x);
long long int __llrint(double __x);
long  int lround(double __x);
long  int __lround(double __x);
long long int llround(double __x);
long long int __llround(double __x);
double fdim(double __x, double __y);
double __fdim(double __x, double __y);
double fmax(double __x, double __y) __attribute__ ((__const__));
double fmin(double __x, double __y) __attribute__ ((__const__));
double fma(double __x, double __y, double __z);
double __fma(double __x, double __y, double __z);
double roundeven(double __x) __attribute__ ((__const__));
long  int  fromfp(double __x, int __round, unsigned int __width);
long  int  __fromfp(double __x, int __round, unsigned int __width);
unsigned long  int  ufromfp(double __x, int __round, unsigned int __width);
unsigned long  int  __ufromfp(double __x, int __round, unsigned int __width);
long  int  fromfpx(double __x, int __round, unsigned int __width);
long  int  __fromfpx(double __x, int __round, unsigned int __width);
unsigned long  int  ufromfpx(double __x, int __round, unsigned int __width);
unsigned long  int  __ufromfpx(double __x, int __round, unsigned int __width);
int canonicalize(double* __cx, const double* __x);
double fmaxmag(double __x, double __y) __attribute__ ((__const__));
double fminmag(double __x, double __y) __attribute__ ((__const__));
double fmaximum(double __x, double __y) __attribute__ ((__const__));
double fminimum(double __x, double __y) __attribute__ ((__const__));
double fmaximum_num(double __x, double __y) __attribute__ ((__const__));
double fminimum_num(double __x, double __y) __attribute__ ((__const__));
double fmaximum_mag(double __x, double __y) __attribute__ ((__const__));
double fminimum_mag(double __x, double __y) __attribute__ ((__const__));
double fmaximum_mag_num(double __x, double __y) __attribute__ ((__const__));
double fminimum_mag_num(double __x, double __y) __attribute__ ((__const__));
int totalorder(const double* __x, const double* __y) __attribute__ ((__pure__));
int totalordermag(const double* __x, const double* __y) __attribute__ ((__pure__));
double getpayload(const double* __x);
double __getpayload(const double* __x);
int setpayload(double* __x, double __payload);
int setpayloadsig(double* __x, double __payload);
double scalb(double __x, double __n);
double __scalb(double __x, double __n);
int __fpclassifyf(float __value) __attribute__ ((__const__));
int __signbitf(float __value) __attribute__ ((__const__));
int __isinff(float __value) __attribute__ ((__const__));
int __finitef(float __value) __attribute__ ((__const__));
int __isnanf(float __value) __attribute__ ((__const__));
int __iseqsigf(float __x, float __y);
int __issignalingf(float __value) __attribute__ ((__const__));
float acosf(float __x);
float __acosf(float __x);
float asinf(float __x);
float __asinf(float __x);
float atanf(float __x);
float __atanf(float __x);
float atan2f(float __y, float __x);
float __atan2f(float __y, float __x);
float cosf(float __x);
float __cosf(float __x);
float sinf(float __x);
float __sinf(float __x);
float tanf(float __x);
float __tanf(float __x);
float acospif(float __x);
float __acospif(float __x);
float asinpif(float __x);
float __asinpif(float __x);
float atanpif(float __x);
float __atanpif(float __x);
float atan2pif(float __y, float __x);
float __atan2pif(float __y, float __x);
float cospif(float __x);
float __cospif(float __x);
float sinpif(float __x);
float __sinpif(float __x);
float tanpif(float __x);
float __tanpif(float __x);
float coshf(float __x);
float __coshf(float __x);
float sinhf(float __x);
float __sinhf(float __x);
float tanhf(float __x);
float __tanhf(float __x);
void sincosf(float __x, float* __sinx, float* __cosx);
void __sincosf(float __x, float* __sinx, float* __cosx);
float acoshf(float __x);
float __acoshf(float __x);
float asinhf(float __x);
float __asinhf(float __x);
float atanhf(float __x);
float __atanhf(float __x);
float expf(float __x);
float __expf(float __x);
float frexpf(float __x, int* __exponent);
float __frexpf(float __x, int* __exponent);
float ldexpf(float __x, int __exponent);
float __ldexpf(float __x, int __exponent);
float logf(float __x);
float __logf(float __x);
float log10f(float __x);
float __log10f(float __x);
float modff(float __x, float* __iptr);
float __modff(float __x, float* __iptr);
float exp10f(float __x);
float __exp10f(float __x);
float exp2m1f(float __x);
float __exp2m1f(float __x);
float exp10m1f(float __x);
float __exp10m1f(float __x);
float log2p1f(float __x);
float __log2p1f(float __x);
float log10p1f(float __x);
float __log10p1f(float __x);
float logp1f(float __x);
float __logp1f(float __x);
float expm1f(float __x);
float __expm1f(float __x);
float log1pf(float __x);
float __log1pf(float __x);
float logbf(float __x);
float __logbf(float __x);
float exp2f(float __x);
float __exp2f(float __x);
float log2f(float __x);
float __log2f(float __x);
float powf(float __x, float __y);
float __powf(float __x, float __y);
float sqrtf(float __x);
float __sqrtf(float __x);
float hypotf(float __x, float __y);
float __hypotf(float __x, float __y);
float cbrtf(float __x);
float __cbrtf(float __x);
float compoundnf(float __x, long long int __y);
float __compoundnf(float __x, long long int __y);
float pownf(float __x, long long int __y);
float __pownf(float __x, long long int __y);
float powrf(float __x, float __y);
float __powrf(float __x, float __y);
float rootnf(float __x, long long int __y);
float __rootnf(float __x, long long int __y);
float rsqrtf(float __x);
float __rsqrtf(float __x);
float ceilf(float __x) __attribute__ ((__const__));
float fabsf(float __x) __attribute__ ((__const__));
float floorf(float __x) __attribute__ ((__const__));
float fmodf(float __x, float __y);
float __fmodf(float __x, float __y);
int isinff(float __value) __attribute__ ((__const__));
int finitef(float __value) __attribute__ ((__const__));
float dremf(float __x, float __y);
float __dremf(float __x, float __y);
float significandf(float __x);
float __significandf(float __x);
float copysignf(float __x, float __y) __attribute__ ((__const__));
float nanf(const char* __tagb);
float __nanf(const char* __tagb);
int isnanf(float __value) __attribute__ ((__const__));
float j0f(float );
float __j0f(float );
float j1f(float );
float __j1f(float );
float jnf(int , float );
float __jnf(int , float );
float y0f(float );
float __y0f(float );
float y1f(float );
float __y1f(float );
float ynf(int , float );
float __ynf(int , float );
float erff(float );
float __erff(float );
float erfcf(float );
float __erfcf(float );
float lgammaf(float );
float __lgammaf(float );
float tgammaf(float );
float __tgammaf(float );
float gammaf(float );
float __gammaf(float );
float lgammaf_r(float , int* __signgamp);
float __lgammaf_r(float , int* __signgamp);
float rintf(float __x);
float __rintf(float __x);
float nextafterf(float __x, float __y);
float __nextafterf(float __x, float __y);
float nexttowardf(float __x, long  double __y);
float __nexttowardf(float __x, long  double __y);
float nextdownf(float __x);
float __nextdownf(float __x);
float nextupf(float __x);
float __nextupf(float __x);
float remainderf(float __x, float __y);
float __remainderf(float __x, float __y);
float scalbnf(float __x, int __n);
float __scalbnf(float __x, int __n);
int ilogbf(float __x);
int __ilogbf(float __x);
long  int llogbf(float __x);
long  int __llogbf(float __x);
float scalblnf(float __x, long  int __n);
float __scalblnf(float __x, long  int __n);
float nearbyintf(float __x);
float __nearbyintf(float __x);
float roundf(float __x) __attribute__ ((__const__));
float truncf(float __x) __attribute__ ((__const__));
float remquof(float __x, float __y, int* __quo);
float __remquof(float __x, float __y, int* __quo);
long  int lrintf(float __x);
long  int __lrintf(float __x);
long long int llrintf(float __x);
long long int __llrintf(float __x);
long  int lroundf(float __x);
long  int __lroundf(float __x);
long long int llroundf(float __x);
long long int __llroundf(float __x);
float fdimf(float __x, float __y);
float __fdimf(float __x, float __y);
float fmaxf(float __x, float __y) __attribute__ ((__const__));
float fminf(float __x, float __y) __attribute__ ((__const__));
float fmaf(float __x, float __y, float __z);
float __fmaf(float __x, float __y, float __z);
float roundevenf(float __x) __attribute__ ((__const__));
long  int  fromfpf(float __x, int __round, unsigned int __width);
long  int  __fromfpf(float __x, int __round, unsigned int __width);
unsigned long  int  ufromfpf(float __x, int __round, unsigned int __width);
unsigned long  int  __ufromfpf(float __x, int __round, unsigned int __width);
long  int  fromfpxf(float __x, int __round, unsigned int __width);
long  int  __fromfpxf(float __x, int __round, unsigned int __width);
unsigned long  int  ufromfpxf(float __x, int __round, unsigned int __width);
unsigned long  int  __ufromfpxf(float __x, int __round, unsigned int __width);
int canonicalizef(float* __cx, const float* __x);
float fmaxmagf(float __x, float __y) __attribute__ ((__const__));
float fminmagf(float __x, float __y) __attribute__ ((__const__));
float fmaximumf(float __x, float __y) __attribute__ ((__const__));
float fminimumf(float __x, float __y) __attribute__ ((__const__));
float fmaximum_numf(float __x, float __y) __attribute__ ((__const__));
float fminimum_numf(float __x, float __y) __attribute__ ((__const__));
float fmaximum_magf(float __x, float __y) __attribute__ ((__const__));
float fminimum_magf(float __x, float __y) __attribute__ ((__const__));
float fmaximum_mag_numf(float __x, float __y) __attribute__ ((__const__));
float fminimum_mag_numf(float __x, float __y) __attribute__ ((__const__));
int totalorderf(const float* __x, const float* __y) __attribute__ ((__pure__));
int totalordermagf(const float* __x, const float* __y) __attribute__ ((__pure__));
float getpayloadf(const float* __x);
float __getpayloadf(const float* __x);
int setpayloadf(float* __x, float __payload);
int setpayloadsigf(float* __x, float __payload);
float scalbf(float __x, float __n);
float __scalbf(float __x, float __n);
int __fpclassifyl(long  double __value) __attribute__ ((__const__));
int __signbitl(long  double __value) __attribute__ ((__const__));
int __isinfl(long  double __value) __attribute__ ((__const__));
int __finitel(long  double __value) __attribute__ ((__const__));
int __isnanl(long  double __value) __attribute__ ((__const__));
int __iseqsigl(long  double __x, long  double __y);
int __issignalingl(long  double __value) __attribute__ ((__const__));
long  double acosl(long  double __x);
long  double __acosl(long  double __x);
long  double asinl(long  double __x);
long  double __asinl(long  double __x);
long  double atanl(long  double __x);
long  double __atanl(long  double __x);
long  double atan2l(long  double __y, long  double __x);
long  double __atan2l(long  double __y, long  double __x);
long  double cosl(long  double __x);
long  double __cosl(long  double __x);
long  double sinl(long  double __x);
long  double __sinl(long  double __x);
long  double tanl(long  double __x);
long  double __tanl(long  double __x);
long  double acospil(long  double __x);
long  double __acospil(long  double __x);
long  double asinpil(long  double __x);
long  double __asinpil(long  double __x);
long  double atanpil(long  double __x);
long  double __atanpil(long  double __x);
long  double atan2pil(long  double __y, long  double __x);
long  double __atan2pil(long  double __y, long  double __x);
long  double cospil(long  double __x);
long  double __cospil(long  double __x);
long  double sinpil(long  double __x);
long  double __sinpil(long  double __x);
long  double tanpil(long  double __x);
long  double __tanpil(long  double __x);
long  double coshl(long  double __x);
long  double __coshl(long  double __x);
long  double sinhl(long  double __x);
long  double __sinhl(long  double __x);
long  double tanhl(long  double __x);
long  double __tanhl(long  double __x);
void sincosl(long  double __x, long  double* __sinx, long  double* __cosx);
void __sincosl(long  double __x, long  double* __sinx, long  double* __cosx);
long  double acoshl(long  double __x);
long  double __acoshl(long  double __x);
long  double asinhl(long  double __x);
long  double __asinhl(long  double __x);
long  double atanhl(long  double __x);
long  double __atanhl(long  double __x);
long  double expl(long  double __x);
long  double __expl(long  double __x);
long  double frexpl(long  double __x, int* __exponent);
long  double __frexpl(long  double __x, int* __exponent);
long  double ldexpl(long  double __x, int __exponent);
long  double __ldexpl(long  double __x, int __exponent);
long  double logl(long  double __x);
long  double __logl(long  double __x);
long  double log10l(long  double __x);
long  double __log10l(long  double __x);
long  double modfl(long  double __x, long  double* __iptr);
long  double __modfl(long  double __x, long  double* __iptr);
long  double exp10l(long  double __x);
long  double __exp10l(long  double __x);
long  double exp2m1l(long  double __x);
long  double __exp2m1l(long  double __x);
long  double exp10m1l(long  double __x);
long  double __exp10m1l(long  double __x);
long  double log2p1l(long  double __x);
long  double __log2p1l(long  double __x);
long  double log10p1l(long  double __x);
long  double __log10p1l(long  double __x);
long  double logp1l(long  double __x);
long  double __logp1l(long  double __x);
long  double expm1l(long  double __x);
long  double __expm1l(long  double __x);
long  double log1pl(long  double __x);
long  double __log1pl(long  double __x);
long  double logbl(long  double __x);
long  double __logbl(long  double __x);
long  double exp2l(long  double __x);
long  double __exp2l(long  double __x);
long  double log2l(long  double __x);
long  double __log2l(long  double __x);
long  double powl(long  double __x, long  double __y);
long  double __powl(long  double __x, long  double __y);
long  double sqrtl(long  double __x);
long  double __sqrtl(long  double __x);
long  double hypotl(long  double __x, long  double __y);
long  double __hypotl(long  double __x, long  double __y);
long  double cbrtl(long  double __x);
long  double __cbrtl(long  double __x);
long  double compoundnl(long  double __x, long long int __y);
long  double __compoundnl(long  double __x, long long int __y);
long  double pownl(long  double __x, long long int __y);
long  double __pownl(long  double __x, long long int __y);
long  double powrl(long  double __x, long  double __y);
long  double __powrl(long  double __x, long  double __y);
long  double rootnl(long  double __x, long long int __y);
long  double __rootnl(long  double __x, long long int __y);
long  double rsqrtl(long  double __x);
long  double __rsqrtl(long  double __x);
long  double ceill(long  double __x) __attribute__ ((__const__));
long  double fabsl(long  double __x) __attribute__ ((__const__));
long  double floorl(long  double __x) __attribute__ ((__const__));
long  double fmodl(long  double __x, long  double __y);
long  double __fmodl(long  double __x, long  double __y);
int isinfl(long  double __value) __attribute__ ((__const__));
int finitel(long  double __value) __attribute__ ((__const__));
long  double dreml(long  double __x, long  double __y);
long  double __dreml(long  double __x, long  double __y);
long  double significandl(long  double __x);
long  double __significandl(long  double __x);
long  double copysignl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double nanl(const char* __tagb);
long  double __nanl(const char* __tagb);
int isnanl(long  double __value) __attribute__ ((__const__));
long  double j0l(long  double );
long  double __j0l(long  double );
long  double j1l(long  double );
long  double __j1l(long  double );
long  double jnl(int , long  double );
long  double __jnl(int , long  double );
long  double y0l(long  double );
long  double __y0l(long  double );
long  double y1l(long  double );
long  double __y1l(long  double );
long  double ynl(int , long  double );
long  double __ynl(int , long  double );
long  double erfl(long  double );
long  double __erfl(long  double );
long  double erfcl(long  double );
long  double __erfcl(long  double );
long  double lgammal(long  double );
long  double __lgammal(long  double );
long  double tgammal(long  double );
long  double __tgammal(long  double );
long  double gammal(long  double );
long  double __gammal(long  double );
long  double lgammal_r(long  double , int* __signgamp);
long  double __lgammal_r(long  double , int* __signgamp);
long  double rintl(long  double __x);
long  double __rintl(long  double __x);
long  double nextafterl(long  double __x, long  double __y);
long  double __nextafterl(long  double __x, long  double __y);
long  double nexttowardl(long  double __x, long  double __y);
long  double __nexttowardl(long  double __x, long  double __y);
long  double nextdownl(long  double __x);
long  double __nextdownl(long  double __x);
long  double nextupl(long  double __x);
long  double __nextupl(long  double __x);
long  double remainderl(long  double __x, long  double __y);
long  double __remainderl(long  double __x, long  double __y);
long  double scalbnl(long  double __x, int __n);
long  double __scalbnl(long  double __x, int __n);
int ilogbl(long  double __x);
int __ilogbl(long  double __x);
long  int llogbl(long  double __x);
long  int __llogbl(long  double __x);
long  double scalblnl(long  double __x, long  int __n);
long  double __scalblnl(long  double __x, long  int __n);
long  double nearbyintl(long  double __x);
long  double __nearbyintl(long  double __x);
long  double roundl(long  double __x) __attribute__ ((__const__));
long  double truncl(long  double __x) __attribute__ ((__const__));
long  double remquol(long  double __x, long  double __y, int* __quo);
long  double __remquol(long  double __x, long  double __y, int* __quo);
long  int lrintl(long  double __x);
long  int __lrintl(long  double __x);
long long int llrintl(long  double __x);
long long int __llrintl(long  double __x);
long  int lroundl(long  double __x);
long  int __lroundl(long  double __x);
long long int llroundl(long  double __x);
long long int __llroundl(long  double __x);
long  double fdiml(long  double __x, long  double __y);
long  double __fdiml(long  double __x, long  double __y);
long  double fmaxl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fminl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fmal(long  double __x, long  double __y, long  double __z);
long  double __fmal(long  double __x, long  double __y, long  double __z);
long  double roundevenl(long  double __x) __attribute__ ((__const__));
long  int  fromfpl(long  double __x, int __round, unsigned int __width);
long  int  __fromfpl(long  double __x, int __round, unsigned int __width);
unsigned long  int  ufromfpl(long  double __x, int __round, unsigned int __width);
unsigned long  int  __ufromfpl(long  double __x, int __round, unsigned int __width);
long  int  fromfpxl(long  double __x, int __round, unsigned int __width);
long  int  __fromfpxl(long  double __x, int __round, unsigned int __width);
unsigned long  int  ufromfpxl(long  double __x, int __round, unsigned int __width);
unsigned long  int  __ufromfpxl(long  double __x, int __round, unsigned int __width);
int canonicalizel(long  double* __cx, const long  double* __x);
long  double fmaxmagl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fminmagl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fmaximuml(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fminimuml(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fmaximum_numl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fminimum_numl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fmaximum_magl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fminimum_magl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fmaximum_mag_numl(long  double __x, long  double __y) __attribute__ ((__const__));
long  double fminimum_mag_numl(long  double __x, long  double __y) __attribute__ ((__const__));
int totalorderl(const long  double* __x, const long  double* __y) __attribute__ ((__pure__));
int totalordermagl(const long  double* __x, const long  double* __y) __attribute__ ((__pure__));
long  double getpayloadl(const long  double* __x);
long  double __getpayloadl(const long  double* __x);
int setpayloadl(long  double* __x, long  double __payload);
int setpayloadsigl(long  double* __x, long  double __payload);
long  double scalbl(long  double __x, long  double __n);
long  double __scalbl(long  double __x, long  double __n);
float  acosf32(float  __x  );
float  __acosf32(float  __x  );
float  asinf32(float  __x  );
float  __asinf32(float  __x  );
float  atanf32(float  __x  );
float  __atanf32(float  __x  );
float  atan2f32(float  __y  , float  __x  );
float  __atan2f32(float  __y  , float  __x  );
float  cosf32(float  __x  );
float  __cosf32(float  __x  );
float  sinf32(float  __x  );
float  __sinf32(float  __x  );
float  tanf32(float  __x  );
float  __tanf32(float  __x  );
float  acospif32(float  __x  );
float  __acospif32(float  __x  );
float  asinpif32(float  __x  );
float  __asinpif32(float  __x  );
float  atanpif32(float  __x  );
float  __atanpif32(float  __x  );
float  atan2pif32(float  __y  , float  __x  );
float  __atan2pif32(float  __y  , float  __x  );
float  cospif32(float  __x  );
float  __cospif32(float  __x  );
float  sinpif32(float  __x  );
float  __sinpif32(float  __x  );
float  tanpif32(float  __x  );
float  __tanpif32(float  __x  );
float  coshf32(float  __x  );
float  __coshf32(float  __x  );
float  sinhf32(float  __x  );
float  __sinhf32(float  __x  );
float  tanhf32(float  __x  );
float  __tanhf32(float  __x  );
void sincosf32(float  __x  , float*  __sinx  , float*  __cosx  );
void __sincosf32(float  __x  , float*  __sinx  , float*  __cosx  );
float  acoshf32(float  __x  );
float  __acoshf32(float  __x  );
float  asinhf32(float  __x  );
float  __asinhf32(float  __x  );
float  atanhf32(float  __x  );
float  __atanhf32(float  __x  );
float  expf32(float  __x  );
float  __expf32(float  __x  );
float  frexpf32(float  __x  , int* __exponent);
float  __frexpf32(float  __x  , int* __exponent);
float  ldexpf32(float  __x  , int __exponent);
float  __ldexpf32(float  __x  , int __exponent);
float  logf32(float  __x  );
float  __logf32(float  __x  );
float  log10f32(float  __x  );
float  __log10f32(float  __x  );
float  modff32(float  __x  , float*  __iptr  );
float  __modff32(float  __x  , float*  __iptr  );
float  exp10f32(float  __x  );
float  __exp10f32(float  __x  );
float  exp2m1f32(float  __x  );
float  __exp2m1f32(float  __x  );
float  exp10m1f32(float  __x  );
float  __exp10m1f32(float  __x  );
float  log2p1f32(float  __x  );
float  __log2p1f32(float  __x  );
float  log10p1f32(float  __x  );
float  __log10p1f32(float  __x  );
float  logp1f32(float  __x  );
float  __logp1f32(float  __x  );
float  expm1f32(float  __x  );
float  __expm1f32(float  __x  );
float  log1pf32(float  __x  );
float  __log1pf32(float  __x  );
float  logbf32(float  __x  );
float  __logbf32(float  __x  );
float  exp2f32(float  __x  );
float  __exp2f32(float  __x  );
float  log2f32(float  __x  );
float  __log2f32(float  __x  );
float  powf32(float  __x  , float  __y  );
float  __powf32(float  __x  , float  __y  );
float  sqrtf32(float  __x  );
float  __sqrtf32(float  __x  );
float  hypotf32(float  __x  , float  __y  );
float  __hypotf32(float  __x  , float  __y  );
float  cbrtf32(float  __x  );
float  __cbrtf32(float  __x  );
float  compoundnf32(float  __x  , long long int __y);
float  __compoundnf32(float  __x  , long long int __y);
float  pownf32(float  __x  , long long int __y);
float  __pownf32(float  __x  , long long int __y);
float  powrf32(float  __x  , float  __y  );
float  __powrf32(float  __x  , float  __y  );
float  rootnf32(float  __x  , long long int __y);
float  __rootnf32(float  __x  , long long int __y);
float  rsqrtf32(float  __x  );
float  __rsqrtf32(float  __x  );
float  ceilf32(float  __x  ) __attribute__ ((__const__));
float  fabsf32(float  __x  ) __attribute__ ((__const__));
float  floorf32(float  __x  ) __attribute__ ((__const__));
float  fmodf32(float  __x  , float  __y  );
float  __fmodf32(float  __x  , float  __y  );
float  copysignf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  nanf32(const char* __tagb);
float  __nanf32(const char* __tagb);
float  j0f32(float    );
float  __j0f32(float    );
float  j1f32(float    );
float  __j1f32(float    );
float  jnf32(int , float    );
float  __jnf32(int , float    );
float  y0f32(float    );
float  __y0f32(float    );
float  y1f32(float    );
float  __y1f32(float    );
float  ynf32(int , float    );
float  __ynf32(int , float    );
float  erff32(float    );
float  __erff32(float    );
float  erfcf32(float    );
float  __erfcf32(float    );
float  lgammaf32(float    );
float  __lgammaf32(float    );
float  tgammaf32(float    );
float  __tgammaf32(float    );
float  lgammaf32_r(float    , int* __signgamp);
float  __lgammaf32_r(float    , int* __signgamp);
float  rintf32(float  __x  );
float  __rintf32(float  __x  );
float  nextafterf32(float  __x  , float  __y  );
float  __nextafterf32(float  __x  , float  __y  );
float  nextdownf32(float  __x  );
float  __nextdownf32(float  __x  );
float  nextupf32(float  __x  );
float  __nextupf32(float  __x  );
float  remainderf32(float  __x  , float  __y  );
float  __remainderf32(float  __x  , float  __y  );
float  scalbnf32(float  __x  , int __n);
float  __scalbnf32(float  __x  , int __n);
int ilogbf32(float  __x  );
int __ilogbf32(float  __x  );
long  int llogbf32(float  __x  );
long  int __llogbf32(float  __x  );
float  scalblnf32(float  __x  , long  int __n);
float  __scalblnf32(float  __x  , long  int __n);
float  nearbyintf32(float  __x  );
float  __nearbyintf32(float  __x  );
float  roundf32(float  __x  ) __attribute__ ((__const__));
float  truncf32(float  __x  ) __attribute__ ((__const__));
float  remquof32(float  __x  , float  __y  , int* __quo);
float  __remquof32(float  __x  , float  __y  , int* __quo);
long  int lrintf32(float  __x  );
long  int __lrintf32(float  __x  );
long long int llrintf32(float  __x  );
long long int __llrintf32(float  __x  );
long  int lroundf32(float  __x  );
long  int __lroundf32(float  __x  );
long long int llroundf32(float  __x  );
long long int __llroundf32(float  __x  );
float  fdimf32(float  __x  , float  __y  );
float  __fdimf32(float  __x  , float  __y  );
float  fmaxf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fminf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fmaf32(float  __x  , float  __y  , float  __z  );
float  __fmaf32(float  __x  , float  __y  , float  __z  );
float  roundevenf32(float  __x  ) __attribute__ ((__const__));
long  int  fromfpf32(float  __x  , int __round, unsigned int __width);
long  int  __fromfpf32(float  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpf32(float  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpf32(float  __x  , int __round, unsigned int __width);
long  int  fromfpxf32(float  __x  , int __round, unsigned int __width);
long  int  __fromfpxf32(float  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpxf32(float  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpxf32(float  __x  , int __round, unsigned int __width);
int canonicalizef32(float*  __cx  , const float*  __x  );
float  fmaxmagf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fminmagf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fmaximumf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fminimumf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fmaximum_numf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fminimum_numf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fmaximum_magf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fminimum_magf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fmaximum_mag_numf32(float  __x  , float  __y  ) __attribute__ ((__const__));
float  fminimum_mag_numf32(float  __x  , float  __y  ) __attribute__ ((__const__));
int totalorderf32(const float*  __x  , const float*  __y  ) __attribute__ ((__pure__));
int totalordermagf32(const float*  __x  , const float*  __y  ) __attribute__ ((__pure__));
float  getpayloadf32(const float*  __x  );
float  __getpayloadf32(const float*  __x  );
int setpayloadf32(float*  __x  , float  __payload  );
int setpayloadsigf32(float*  __x  , float  __payload  );
double  acosf64(double  __x  );
double  __acosf64(double  __x  );
double  asinf64(double  __x  );
double  __asinf64(double  __x  );
double  atanf64(double  __x  );
double  __atanf64(double  __x  );
double  atan2f64(double  __y  , double  __x  );
double  __atan2f64(double  __y  , double  __x  );
double  cosf64(double  __x  );
double  __cosf64(double  __x  );
double  sinf64(double  __x  );
double  __sinf64(double  __x  );
double  tanf64(double  __x  );
double  __tanf64(double  __x  );
double  acospif64(double  __x  );
double  __acospif64(double  __x  );
double  asinpif64(double  __x  );
double  __asinpif64(double  __x  );
double  atanpif64(double  __x  );
double  __atanpif64(double  __x  );
double  atan2pif64(double  __y  , double  __x  );
double  __atan2pif64(double  __y  , double  __x  );
double  cospif64(double  __x  );
double  __cospif64(double  __x  );
double  sinpif64(double  __x  );
double  __sinpif64(double  __x  );
double  tanpif64(double  __x  );
double  __tanpif64(double  __x  );
double  coshf64(double  __x  );
double  __coshf64(double  __x  );
double  sinhf64(double  __x  );
double  __sinhf64(double  __x  );
double  tanhf64(double  __x  );
double  __tanhf64(double  __x  );
void sincosf64(double  __x  , double*  __sinx  , double*  __cosx  );
void __sincosf64(double  __x  , double*  __sinx  , double*  __cosx  );
double  acoshf64(double  __x  );
double  __acoshf64(double  __x  );
double  asinhf64(double  __x  );
double  __asinhf64(double  __x  );
double  atanhf64(double  __x  );
double  __atanhf64(double  __x  );
double  expf64(double  __x  );
double  __expf64(double  __x  );
double  frexpf64(double  __x  , int* __exponent);
double  __frexpf64(double  __x  , int* __exponent);
double  ldexpf64(double  __x  , int __exponent);
double  __ldexpf64(double  __x  , int __exponent);
double  logf64(double  __x  );
double  __logf64(double  __x  );
double  log10f64(double  __x  );
double  __log10f64(double  __x  );
double  modff64(double  __x  , double*  __iptr  );
double  __modff64(double  __x  , double*  __iptr  );
double  exp10f64(double  __x  );
double  __exp10f64(double  __x  );
double  exp2m1f64(double  __x  );
double  __exp2m1f64(double  __x  );
double  exp10m1f64(double  __x  );
double  __exp10m1f64(double  __x  );
double  log2p1f64(double  __x  );
double  __log2p1f64(double  __x  );
double  log10p1f64(double  __x  );
double  __log10p1f64(double  __x  );
double  logp1f64(double  __x  );
double  __logp1f64(double  __x  );
double  expm1f64(double  __x  );
double  __expm1f64(double  __x  );
double  log1pf64(double  __x  );
double  __log1pf64(double  __x  );
double  logbf64(double  __x  );
double  __logbf64(double  __x  );
double  exp2f64(double  __x  );
double  __exp2f64(double  __x  );
double  log2f64(double  __x  );
double  __log2f64(double  __x  );
double  powf64(double  __x  , double  __y  );
double  __powf64(double  __x  , double  __y  );
double  sqrtf64(double  __x  );
double  __sqrtf64(double  __x  );
double  hypotf64(double  __x  , double  __y  );
double  __hypotf64(double  __x  , double  __y  );
double  cbrtf64(double  __x  );
double  __cbrtf64(double  __x  );
double  compoundnf64(double  __x  , long long int __y);
double  __compoundnf64(double  __x  , long long int __y);
double  pownf64(double  __x  , long long int __y);
double  __pownf64(double  __x  , long long int __y);
double  powrf64(double  __x  , double  __y  );
double  __powrf64(double  __x  , double  __y  );
double  rootnf64(double  __x  , long long int __y);
double  __rootnf64(double  __x  , long long int __y);
double  rsqrtf64(double  __x  );
double  __rsqrtf64(double  __x  );
double  ceilf64(double  __x  ) __attribute__ ((__const__));
double  fabsf64(double  __x  ) __attribute__ ((__const__));
double  floorf64(double  __x  ) __attribute__ ((__const__));
double  fmodf64(double  __x  , double  __y  );
double  __fmodf64(double  __x  , double  __y  );
double  copysignf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  nanf64(const char* __tagb);
double  __nanf64(const char* __tagb);
double  j0f64(double    );
double  __j0f64(double    );
double  j1f64(double    );
double  __j1f64(double    );
double  jnf64(int , double    );
double  __jnf64(int , double    );
double  y0f64(double    );
double  __y0f64(double    );
double  y1f64(double    );
double  __y1f64(double    );
double  ynf64(int , double    );
double  __ynf64(int , double    );
double  erff64(double    );
double  __erff64(double    );
double  erfcf64(double    );
double  __erfcf64(double    );
double  lgammaf64(double    );
double  __lgammaf64(double    );
double  tgammaf64(double    );
double  __tgammaf64(double    );
double  lgammaf64_r(double    , int* __signgamp);
double  __lgammaf64_r(double    , int* __signgamp);
double  rintf64(double  __x  );
double  __rintf64(double  __x  );
double  nextafterf64(double  __x  , double  __y  );
double  __nextafterf64(double  __x  , double  __y  );
double  nextdownf64(double  __x  );
double  __nextdownf64(double  __x  );
double  nextupf64(double  __x  );
double  __nextupf64(double  __x  );
double  remainderf64(double  __x  , double  __y  );
double  __remainderf64(double  __x  , double  __y  );
double  scalbnf64(double  __x  , int __n);
double  __scalbnf64(double  __x  , int __n);
int ilogbf64(double  __x  );
int __ilogbf64(double  __x  );
long  int llogbf64(double  __x  );
long  int __llogbf64(double  __x  );
double  scalblnf64(double  __x  , long  int __n);
double  __scalblnf64(double  __x  , long  int __n);
double  nearbyintf64(double  __x  );
double  __nearbyintf64(double  __x  );
double  roundf64(double  __x  ) __attribute__ ((__const__));
double  truncf64(double  __x  ) __attribute__ ((__const__));
double  remquof64(double  __x  , double  __y  , int* __quo);
double  __remquof64(double  __x  , double  __y  , int* __quo);
long  int lrintf64(double  __x  );
long  int __lrintf64(double  __x  );
long long int llrintf64(double  __x  );
long long int __llrintf64(double  __x  );
long  int lroundf64(double  __x  );
long  int __lroundf64(double  __x  );
long long int llroundf64(double  __x  );
long long int __llroundf64(double  __x  );
double  fdimf64(double  __x  , double  __y  );
double  __fdimf64(double  __x  , double  __y  );
double  fmaxf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaf64(double  __x  , double  __y  , double  __z  );
double  __fmaf64(double  __x  , double  __y  , double  __z  );
double  roundevenf64(double  __x  ) __attribute__ ((__const__));
long  int  fromfpf64(double  __x  , int __round, unsigned int __width);
long  int  __fromfpf64(double  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpf64(double  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpf64(double  __x  , int __round, unsigned int __width);
long  int  fromfpxf64(double  __x  , int __round, unsigned int __width);
long  int  __fromfpxf64(double  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpxf64(double  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpxf64(double  __x  , int __round, unsigned int __width);
int canonicalizef64(double*  __cx  , const double*  __x  );
double  fmaxmagf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminmagf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximumf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimumf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximum_numf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimum_numf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximum_magf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimum_magf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximum_mag_numf64(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimum_mag_numf64(double  __x  , double  __y  ) __attribute__ ((__const__));
int totalorderf64(const double*  __x  , const double*  __y  ) __attribute__ ((__pure__));
int totalordermagf64(const double*  __x  , const double*  __y  ) __attribute__ ((__pure__));
double  getpayloadf64(const double*  __x  );
double  __getpayloadf64(const double*  __x  );
int setpayloadf64(double*  __x  , double  __payload  );
int setpayloadsigf64(double*  __x  , double  __payload  );
double  acosf32x(double  __x  );
double  __acosf32x(double  __x  );
double  asinf32x(double  __x  );
double  __asinf32x(double  __x  );
double  atanf32x(double  __x  );
double  __atanf32x(double  __x  );
double  atan2f32x(double  __y  , double  __x  );
double  __atan2f32x(double  __y  , double  __x  );
double  cosf32x(double  __x  );
double  __cosf32x(double  __x  );
double  sinf32x(double  __x  );
double  __sinf32x(double  __x  );
double  tanf32x(double  __x  );
double  __tanf32x(double  __x  );
double  acospif32x(double  __x  );
double  __acospif32x(double  __x  );
double  asinpif32x(double  __x  );
double  __asinpif32x(double  __x  );
double  atanpif32x(double  __x  );
double  __atanpif32x(double  __x  );
double  atan2pif32x(double  __y  , double  __x  );
double  __atan2pif32x(double  __y  , double  __x  );
double  cospif32x(double  __x  );
double  __cospif32x(double  __x  );
double  sinpif32x(double  __x  );
double  __sinpif32x(double  __x  );
double  tanpif32x(double  __x  );
double  __tanpif32x(double  __x  );
double  coshf32x(double  __x  );
double  __coshf32x(double  __x  );
double  sinhf32x(double  __x  );
double  __sinhf32x(double  __x  );
double  tanhf32x(double  __x  );
double  __tanhf32x(double  __x  );
void sincosf32x(double  __x  , double*  __sinx  , double*  __cosx  );
void __sincosf32x(double  __x  , double*  __sinx  , double*  __cosx  );
double  acoshf32x(double  __x  );
double  __acoshf32x(double  __x  );
double  asinhf32x(double  __x  );
double  __asinhf32x(double  __x  );
double  atanhf32x(double  __x  );
double  __atanhf32x(double  __x  );
double  expf32x(double  __x  );
double  __expf32x(double  __x  );
double  frexpf32x(double  __x  , int* __exponent);
double  __frexpf32x(double  __x  , int* __exponent);
double  ldexpf32x(double  __x  , int __exponent);
double  __ldexpf32x(double  __x  , int __exponent);
double  logf32x(double  __x  );
double  __logf32x(double  __x  );
double  log10f32x(double  __x  );
double  __log10f32x(double  __x  );
double  modff32x(double  __x  , double*  __iptr  );
double  __modff32x(double  __x  , double*  __iptr  );
double  exp10f32x(double  __x  );
double  __exp10f32x(double  __x  );
double  exp2m1f32x(double  __x  );
double  __exp2m1f32x(double  __x  );
double  exp10m1f32x(double  __x  );
double  __exp10m1f32x(double  __x  );
double  log2p1f32x(double  __x  );
double  __log2p1f32x(double  __x  );
double  log10p1f32x(double  __x  );
double  __log10p1f32x(double  __x  );
double  logp1f32x(double  __x  );
double  __logp1f32x(double  __x  );
double  expm1f32x(double  __x  );
double  __expm1f32x(double  __x  );
double  log1pf32x(double  __x  );
double  __log1pf32x(double  __x  );
double  logbf32x(double  __x  );
double  __logbf32x(double  __x  );
double  exp2f32x(double  __x  );
double  __exp2f32x(double  __x  );
double  log2f32x(double  __x  );
double  __log2f32x(double  __x  );
double  powf32x(double  __x  , double  __y  );
double  __powf32x(double  __x  , double  __y  );
double  sqrtf32x(double  __x  );
double  __sqrtf32x(double  __x  );
double  hypotf32x(double  __x  , double  __y  );
double  __hypotf32x(double  __x  , double  __y  );
double  cbrtf32x(double  __x  );
double  __cbrtf32x(double  __x  );
double  compoundnf32x(double  __x  , long long int __y);
double  __compoundnf32x(double  __x  , long long int __y);
double  pownf32x(double  __x  , long long int __y);
double  __pownf32x(double  __x  , long long int __y);
double  powrf32x(double  __x  , double  __y  );
double  __powrf32x(double  __x  , double  __y  );
double  rootnf32x(double  __x  , long long int __y);
double  __rootnf32x(double  __x  , long long int __y);
double  rsqrtf32x(double  __x  );
double  __rsqrtf32x(double  __x  );
double  ceilf32x(double  __x  ) __attribute__ ((__const__));
double  fabsf32x(double  __x  ) __attribute__ ((__const__));
double  floorf32x(double  __x  ) __attribute__ ((__const__));
double  fmodf32x(double  __x  , double  __y  );
double  __fmodf32x(double  __x  , double  __y  );
double  copysignf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  nanf32x(const char* __tagb);
double  __nanf32x(const char* __tagb);
double  j0f32x(double    );
double  __j0f32x(double    );
double  j1f32x(double    );
double  __j1f32x(double    );
double  jnf32x(int , double    );
double  __jnf32x(int , double    );
double  y0f32x(double    );
double  __y0f32x(double    );
double  y1f32x(double    );
double  __y1f32x(double    );
double  ynf32x(int , double    );
double  __ynf32x(int , double    );
double  erff32x(double    );
double  __erff32x(double    );
double  erfcf32x(double    );
double  __erfcf32x(double    );
double  lgammaf32x(double    );
double  __lgammaf32x(double    );
double  tgammaf32x(double    );
double  __tgammaf32x(double    );
double  lgammaf32x_r(double    , int* __signgamp);
double  __lgammaf32x_r(double    , int* __signgamp);
double  rintf32x(double  __x  );
double  __rintf32x(double  __x  );
double  nextafterf32x(double  __x  , double  __y  );
double  __nextafterf32x(double  __x  , double  __y  );
double  nextdownf32x(double  __x  );
double  __nextdownf32x(double  __x  );
double  nextupf32x(double  __x  );
double  __nextupf32x(double  __x  );
double  remainderf32x(double  __x  , double  __y  );
double  __remainderf32x(double  __x  , double  __y  );
double  scalbnf32x(double  __x  , int __n);
double  __scalbnf32x(double  __x  , int __n);
int ilogbf32x(double  __x  );
int __ilogbf32x(double  __x  );
long  int llogbf32x(double  __x  );
long  int __llogbf32x(double  __x  );
double  scalblnf32x(double  __x  , long  int __n);
double  __scalblnf32x(double  __x  , long  int __n);
double  nearbyintf32x(double  __x  );
double  __nearbyintf32x(double  __x  );
double  roundf32x(double  __x  ) __attribute__ ((__const__));
double  truncf32x(double  __x  ) __attribute__ ((__const__));
double  remquof32x(double  __x  , double  __y  , int* __quo);
double  __remquof32x(double  __x  , double  __y  , int* __quo);
long  int lrintf32x(double  __x  );
long  int __lrintf32x(double  __x  );
long long int llrintf32x(double  __x  );
long long int __llrintf32x(double  __x  );
long  int lroundf32x(double  __x  );
long  int __lroundf32x(double  __x  );
long long int llroundf32x(double  __x  );
long long int __llroundf32x(double  __x  );
double  fdimf32x(double  __x  , double  __y  );
double  __fdimf32x(double  __x  , double  __y  );
double  fmaxf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaf32x(double  __x  , double  __y  , double  __z  );
double  __fmaf32x(double  __x  , double  __y  , double  __z  );
double  roundevenf32x(double  __x  ) __attribute__ ((__const__));
long  int  fromfpf32x(double  __x  , int __round, unsigned int __width);
long  int  __fromfpf32x(double  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpf32x(double  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpf32x(double  __x  , int __round, unsigned int __width);
long  int  fromfpxf32x(double  __x  , int __round, unsigned int __width);
long  int  __fromfpxf32x(double  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpxf32x(double  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpxf32x(double  __x  , int __round, unsigned int __width);
int canonicalizef32x(double*  __cx  , const double*  __x  );
double  fmaxmagf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminmagf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximumf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimumf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximum_numf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimum_numf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximum_magf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimum_magf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fmaximum_mag_numf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
double  fminimum_mag_numf32x(double  __x  , double  __y  ) __attribute__ ((__const__));
int totalorderf32x(const double*  __x  , const double*  __y  ) __attribute__ ((__pure__));
int totalordermagf32x(const double*  __x  , const double*  __y  ) __attribute__ ((__pure__));
double  getpayloadf32x(const double*  __x  );
double  __getpayloadf32x(const double*  __x  );
int setpayloadf32x(double*  __x  , double  __payload  );
int setpayloadsigf32x(double*  __x  , double  __payload  );
long  double  acosf64x(long  double  __x  );
long  double  __acosf64x(long  double  __x  );
long  double  asinf64x(long  double  __x  );
long  double  __asinf64x(long  double  __x  );
long  double  atanf64x(long  double  __x  );
long  double  __atanf64x(long  double  __x  );
long  double  atan2f64x(long  double  __y  , long  double  __x  );
long  double  __atan2f64x(long  double  __y  , long  double  __x  );
long  double  cosf64x(long  double  __x  );
long  double  __cosf64x(long  double  __x  );
long  double  sinf64x(long  double  __x  );
long  double  __sinf64x(long  double  __x  );
long  double  tanf64x(long  double  __x  );
long  double  __tanf64x(long  double  __x  );
long  double  acospif64x(long  double  __x  );
long  double  __acospif64x(long  double  __x  );
long  double  asinpif64x(long  double  __x  );
long  double  __asinpif64x(long  double  __x  );
long  double  atanpif64x(long  double  __x  );
long  double  __atanpif64x(long  double  __x  );
long  double  atan2pif64x(long  double  __y  , long  double  __x  );
long  double  __atan2pif64x(long  double  __y  , long  double  __x  );
long  double  cospif64x(long  double  __x  );
long  double  __cospif64x(long  double  __x  );
long  double  sinpif64x(long  double  __x  );
long  double  __sinpif64x(long  double  __x  );
long  double  tanpif64x(long  double  __x  );
long  double  __tanpif64x(long  double  __x  );
long  double  coshf64x(long  double  __x  );
long  double  __coshf64x(long  double  __x  );
long  double  sinhf64x(long  double  __x  );
long  double  __sinhf64x(long  double  __x  );
long  double  tanhf64x(long  double  __x  );
long  double  __tanhf64x(long  double  __x  );
void sincosf64x(long  double  __x  , long  double*  __sinx  , long  double*  __cosx  );
void __sincosf64x(long  double  __x  , long  double*  __sinx  , long  double*  __cosx  );
long  double  acoshf64x(long  double  __x  );
long  double  __acoshf64x(long  double  __x  );
long  double  asinhf64x(long  double  __x  );
long  double  __asinhf64x(long  double  __x  );
long  double  atanhf64x(long  double  __x  );
long  double  __atanhf64x(long  double  __x  );
long  double  expf64x(long  double  __x  );
long  double  __expf64x(long  double  __x  );
long  double  frexpf64x(long  double  __x  , int* __exponent);
long  double  __frexpf64x(long  double  __x  , int* __exponent);
long  double  ldexpf64x(long  double  __x  , int __exponent);
long  double  __ldexpf64x(long  double  __x  , int __exponent);
long  double  logf64x(long  double  __x  );
long  double  __logf64x(long  double  __x  );
long  double  log10f64x(long  double  __x  );
long  double  __log10f64x(long  double  __x  );
long  double  modff64x(long  double  __x  , long  double*  __iptr  );
long  double  __modff64x(long  double  __x  , long  double*  __iptr  );
long  double  exp10f64x(long  double  __x  );
long  double  __exp10f64x(long  double  __x  );
long  double  exp2m1f64x(long  double  __x  );
long  double  __exp2m1f64x(long  double  __x  );
long  double  exp10m1f64x(long  double  __x  );
long  double  __exp10m1f64x(long  double  __x  );
long  double  log2p1f64x(long  double  __x  );
long  double  __log2p1f64x(long  double  __x  );
long  double  log10p1f64x(long  double  __x  );
long  double  __log10p1f64x(long  double  __x  );
long  double  logp1f64x(long  double  __x  );
long  double  __logp1f64x(long  double  __x  );
long  double  expm1f64x(long  double  __x  );
long  double  __expm1f64x(long  double  __x  );
long  double  log1pf64x(long  double  __x  );
long  double  __log1pf64x(long  double  __x  );
long  double  logbf64x(long  double  __x  );
long  double  __logbf64x(long  double  __x  );
long  double  exp2f64x(long  double  __x  );
long  double  __exp2f64x(long  double  __x  );
long  double  log2f64x(long  double  __x  );
long  double  __log2f64x(long  double  __x  );
long  double  powf64x(long  double  __x  , long  double  __y  );
long  double  __powf64x(long  double  __x  , long  double  __y  );
long  double  sqrtf64x(long  double  __x  );
long  double  __sqrtf64x(long  double  __x  );
long  double  hypotf64x(long  double  __x  , long  double  __y  );
long  double  __hypotf64x(long  double  __x  , long  double  __y  );
long  double  cbrtf64x(long  double  __x  );
long  double  __cbrtf64x(long  double  __x  );
long  double  compoundnf64x(long  double  __x  , long long int __y);
long  double  __compoundnf64x(long  double  __x  , long long int __y);
long  double  pownf64x(long  double  __x  , long long int __y);
long  double  __pownf64x(long  double  __x  , long long int __y);
long  double  powrf64x(long  double  __x  , long  double  __y  );
long  double  __powrf64x(long  double  __x  , long  double  __y  );
long  double  rootnf64x(long  double  __x  , long long int __y);
long  double  __rootnf64x(long  double  __x  , long long int __y);
long  double  rsqrtf64x(long  double  __x  );
long  double  __rsqrtf64x(long  double  __x  );
long  double  ceilf64x(long  double  __x  ) __attribute__ ((__const__));
long  double  fabsf64x(long  double  __x  ) __attribute__ ((__const__));
long  double  floorf64x(long  double  __x  ) __attribute__ ((__const__));
long  double  fmodf64x(long  double  __x  , long  double  __y  );
long  double  __fmodf64x(long  double  __x  , long  double  __y  );
long  double  copysignf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  nanf64x(const char* __tagb);
long  double  __nanf64x(const char* __tagb);
long  double  j0f64x(long  double    );
long  double  __j0f64x(long  double    );
long  double  j1f64x(long  double    );
long  double  __j1f64x(long  double    );
long  double  jnf64x(int , long  double    );
long  double  __jnf64x(int , long  double    );
long  double  y0f64x(long  double    );
long  double  __y0f64x(long  double    );
long  double  y1f64x(long  double    );
long  double  __y1f64x(long  double    );
long  double  ynf64x(int , long  double    );
long  double  __ynf64x(int , long  double    );
long  double  erff64x(long  double    );
long  double  __erff64x(long  double    );
long  double  erfcf64x(long  double    );
long  double  __erfcf64x(long  double    );
long  double  lgammaf64x(long  double    );
long  double  __lgammaf64x(long  double    );
long  double  tgammaf64x(long  double    );
long  double  __tgammaf64x(long  double    );
long  double  lgammaf64x_r(long  double    , int* __signgamp);
long  double  __lgammaf64x_r(long  double    , int* __signgamp);
long  double  rintf64x(long  double  __x  );
long  double  __rintf64x(long  double  __x  );
long  double  nextafterf64x(long  double  __x  , long  double  __y  );
long  double  __nextafterf64x(long  double  __x  , long  double  __y  );
long  double  nextdownf64x(long  double  __x  );
long  double  __nextdownf64x(long  double  __x  );
long  double  nextupf64x(long  double  __x  );
long  double  __nextupf64x(long  double  __x  );
long  double  remainderf64x(long  double  __x  , long  double  __y  );
long  double  __remainderf64x(long  double  __x  , long  double  __y  );
long  double  scalbnf64x(long  double  __x  , int __n);
long  double  __scalbnf64x(long  double  __x  , int __n);
int ilogbf64x(long  double  __x  );
int __ilogbf64x(long  double  __x  );
long  int llogbf64x(long  double  __x  );
long  int __llogbf64x(long  double  __x  );
long  double  scalblnf64x(long  double  __x  , long  int __n);
long  double  __scalblnf64x(long  double  __x  , long  int __n);
long  double  nearbyintf64x(long  double  __x  );
long  double  __nearbyintf64x(long  double  __x  );
long  double  roundf64x(long  double  __x  ) __attribute__ ((__const__));
long  double  truncf64x(long  double  __x  ) __attribute__ ((__const__));
long  double  remquof64x(long  double  __x  , long  double  __y  , int* __quo);
long  double  __remquof64x(long  double  __x  , long  double  __y  , int* __quo);
long  int lrintf64x(long  double  __x  );
long  int __lrintf64x(long  double  __x  );
long long int llrintf64x(long  double  __x  );
long long int __llrintf64x(long  double  __x  );
long  int lroundf64x(long  double  __x  );
long  int __lroundf64x(long  double  __x  );
long long int llroundf64x(long  double  __x  );
long long int __llroundf64x(long  double  __x  );
long  double  fdimf64x(long  double  __x  , long  double  __y  );
long  double  __fdimf64x(long  double  __x  , long  double  __y  );
long  double  fmaxf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fminf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fmaf64x(long  double  __x  , long  double  __y  , long  double  __z  );
long  double  __fmaf64x(long  double  __x  , long  double  __y  , long  double  __z  );
long  double  roundevenf64x(long  double  __x  ) __attribute__ ((__const__));
long  int  fromfpf64x(long  double  __x  , int __round, unsigned int __width);
long  int  __fromfpf64x(long  double  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpf64x(long  double  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpf64x(long  double  __x  , int __round, unsigned int __width);
long  int  fromfpxf64x(long  double  __x  , int __round, unsigned int __width);
long  int  __fromfpxf64x(long  double  __x  , int __round, unsigned int __width);
unsigned long  int  ufromfpxf64x(long  double  __x  , int __round, unsigned int __width);
unsigned long  int  __ufromfpxf64x(long  double  __x  , int __round, unsigned int __width);
int canonicalizef64x(long  double*  __cx  , const long  double*  __x  );
long  double  fmaxmagf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fminmagf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fmaximumf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fminimumf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fmaximum_numf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fminimum_numf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fmaximum_magf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fminimum_magf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fmaximum_mag_numf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
long  double  fminimum_mag_numf64x(long  double  __x  , long  double  __y  ) __attribute__ ((__const__));
int totalorderf64x(const long  double*  __x  , const long  double*  __y  ) __attribute__ ((__pure__));
int totalordermagf64x(const long  double*  __x  , const long  double*  __y  ) __attribute__ ((__pure__));
long  double  getpayloadf64x(const long  double*  __x  );
long  double  __getpayloadf64x(const long  double*  __x  );
int setpayloadf64x(long  double*  __x  , long  double  __payload  );
int setpayloadsigf64x(long  double*  __x  , long  double  __payload  );
float fadd(double __x, double __y);
float fdiv(double __x, double __y);
float ffma(double __x, double __y, double __z);
float fmul(double __x, double __y);
float fsqrt(double __x);
float fsub(double __x, double __y);
float faddl(long  double __x, long  double __y);
float fdivl(long  double __x, long  double __y);
float ffmal(long  double __x, long  double __y, long  double __z);
float fmull(long  double __x, long  double __y);
float fsqrtl(long  double __x);
float fsubl(long  double __x, long  double __y);
double daddl(long  double __x, long  double __y);
double ddivl(long  double __x, long  double __y);
double dfmal(long  double __x, long  double __y, long  double __z);
double dmull(long  double __x, long  double __y);
double dsqrtl(long  double __x);
double dsubl(long  double __x, long  double __y);
float  f32addf32x(double  __x  , double  __y  );
float  f32divf32x(double  __x  , double  __y  );
float  f32fmaf32x(double  __x  , double  __y  , double  __z  );
float  f32mulf32x(double  __x  , double  __y  );
float  f32sqrtf32x(double  __x  );
float  f32subf32x(double  __x  , double  __y  );
float  f32addf64(double  __x  , double  __y  );
float  f32divf64(double  __x  , double  __y  );
float  f32fmaf64(double  __x  , double  __y  , double  __z  );
float  f32mulf64(double  __x  , double  __y  );
float  f32sqrtf64(double  __x  );
float  f32subf64(double  __x  , double  __y  );
float  f32addf64x(long  double  __x  , long  double  __y  );
float  f32divf64x(long  double  __x  , long  double  __y  );
float  f32fmaf64x(long  double  __x  , long  double  __y  , long  double  __z  );
float  f32mulf64x(long  double  __x  , long  double  __y  );
float  f32sqrtf64x(long  double  __x  );
float  f32subf64x(long  double  __x  , long  double  __y  );
double  f32xaddf64(double  __x  , double  __y  );
double  f32xdivf64(double  __x  , double  __y  );
double  f32xfmaf64(double  __x  , double  __y  , double  __z  );
double  f32xmulf64(double  __x  , double  __y  );
double  f32xsqrtf64(double  __x  );
double  f32xsubf64(double  __x  , double  __y  );
double  f32xaddf64x(long  double  __x  , long  double  __y  );
double  f32xdivf64x(long  double  __x  , long  double  __y  );
double  f32xfmaf64x(long  double  __x  , long  double  __y  , long  double  __z  );
double  f32xmulf64x(long  double  __x  , long  double  __y  );
double  f32xsqrtf64x(long  double  __x  );
double  f32xsubf64x(long  double  __x  , long  double  __y  );
double  f64addf64x(long  double  __x  , long  double  __y  );
double  f64divf64x(long  double  __x  , long  double  __y  );
double  f64fmaf64x(long  double  __x  , long  double  __y  , long  double  __z  );
double  f64mulf64x(long  double  __x  , long  double  __y  );
double  f64sqrtf64x(long  double  __x  );
double  f64subf64x(long  double  __x  , long  double  __y  );
int __iscanonicall(long  double __x) __attribute__ ((__const__));
static _Bool approxf(float a, float b, float eps);
static _Bool approx(double a, double b, double eps);
int main();
// uniq global variable
// inline function

// body function
static _Bool approxf(float a, float b, float eps)
{
    float diff;
    diff=a-b;
    if(diff<0) {
        diff=-diff;
    }
        return diff<=eps;
}

static _Bool approx(double a, double b, double eps)
{
    double diff;
    diff=a-b;
    if(diff<0) {
        diff=-diff;
    }
        return diff<=eps;
}

int main()
{
    _Bool ok;
    int hx;
    float f;
    double d;
    long l;
    unsigned long  int ul;
    ok=(_Bool)1;
    hx=0x01;
    ok=ok&&(hx==1);
    f=1.1f;
    ok=ok&&approxf(f,1.1f,1e-6f);
    d=1.2;
    ok=ok&&approx(d,1.2,1e-12);
    l=22L;
    ul=22UL;
    ok=ok&&(l==22L)&&(ul==22UL);
    if(ok) {
        puts("OK");
                return 0;
    }
    else {
        puts("NG");
                return 1;
    }
}

